"""SMD text parser for the format used by Main 5.2.

This parser intentionally handles the documented text sections and preserves
unknown data as diagnostics instead of guessing. It is suitable for an
offline conversion pipeline, not for the legacy runtime.
"""
from __future__ import annotations

from dataclasses import dataclass, asdict
from pathlib import Path
import json
import re
from typing import Any


@dataclass
class Node:
    index: int
    name: str
    parent: int


@dataclass
class Vertex:
    bone: int
    position: list[float]
    normal: list[float]
    uv: list[float]


@dataclass
class Triangle:
    texture: str
    vertices: list[Vertex]


def _section(text: str, name: str) -> str | None:
    match = re.search(rf"(?ms)^\s*{re.escape(name)}\s*\{{(.*?)^\s*\}}", text)
    return match.group(1) if match else None


def _numbers(line: str) -> list[str]:
    return line.strip().split()


def parse_smd(path: str | Path) -> dict[str, Any]:
    source = Path(path)
    text = source.read_text(encoding="utf-8-sig", errors="replace")
    result: dict[str, Any] = {
        "format": "MuSMD",
        "version": 1,
        "source": source.name,
        "nodes": [],
        "animations": [],
        "triangles": [],
        "diagnostics": [],
    }

    nodes = _section(text, "nodes")
    if nodes is not None:
        for line in nodes.splitlines():
            line = line.strip()
            if not line or line.startswith("//"):
                continue
            match = re.match(r'(\d+)\s+"(.*?)"\s+(-?\d+)', line)
            if not match:
                result["diagnostics"].append(f"unparsed nodes line: {line}")
                continue
            result["nodes"].append(asdict(Node(int(match[1]), match[2], int(match[3]))))
    else:
        result["diagnostics"].append("missing nodes section")

    triangles = _section(text, "triangles")
    if triangles is not None:
        lines = [line.strip() for line in triangles.splitlines() if line.strip()]
        index = 0
        while index < len(lines):
            texture = lines[index]
            if texture.startswith("//"):
                index += 1
                continue
            if index + 3 >= len(lines):
                result["diagnostics"].append("incomplete triangle at end of file")
                break
            values: list[Vertex] = []
            for vertex_line in lines[index + 1:index + 4]:
                values_raw = _numbers(vertex_line)
                if len(values_raw) < 9:
                    result["diagnostics"].append(f"invalid triangle vertex: {vertex_line}")
                    continue
                values.append(asdict(Vertex(
                    bone=int(values_raw[0]),
                    position=[float(values_raw[1]), float(values_raw[2]), float(values_raw[3])],
                    normal=[float(values_raw[4]), float(values_raw[5]), float(values_raw[6])],
                    uv=[float(values_raw[7]), float(values_raw[8])],
                )))
            if len(values) == 3:
                result["triangles"].append(asdict(Triangle(texture, values)))
            index += 4
    else:
        result["diagnostics"].append("missing triangles section")

    skeleton = _section(text, "skeleton")
    if skeleton is not None:
        result["diagnostics"].append("skeleton section detected; animation export is not implemented yet")
        result["skeletonPresent"] = True
    else:
        result["skeletonPresent"] = False
    return result


def write_json(data: dict[str, Any], output: str | Path) -> None:
    Path(output).parent.mkdir(parents=True, exist_ok=True)
    Path(output).write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_obj(data: dict[str, Any], output: str | Path) -> None:
    out = Path(output)
    out.parent.mkdir(parents=True, exist_ok=True)
    vertices: list[list[float]] = []
    uvs: list[list[float]] = []
    normals: list[list[float]] = []
    faces: list[tuple[str, list[tuple[int, int, int]]]] = []
    for triangle in data.get("triangles", []):
        face = []
        for vertex in triangle["vertices"]:
            vertices.append(vertex["position"])
            normals.append(vertex["normal"])
            uvs.append([vertex["uv"][0], 1.0 - vertex["uv"][1]])
            i = len(vertices)
            face.append((i, i, i))
        faces.append((triangle["texture"], face))
    with out.open("w", encoding="utf-8") as stream:
        stream.write(f"# Generated by MuAssetTool from {data.get('source', '')}\n")
        for value in vertices:
            stream.write(f"v {value[0]} {value[1]} {value[2]}\n")
        for value in uvs:
            stream.write(f"vt {value[0]} {value[1]}\n")
        for value in normals:
            stream.write(f"vn {value[0]} {value[1]} {value[2]}\n")
        current = None
        for texture, face in faces:
            if texture != current:
                stream.write(f"g {Path(texture).stem or 'mesh'}\n")
                current = texture
            stream.write("f " + " ".join(f"{v}/{u}/{n}" for v, u, n in face) + "\n")
